### ISSUE TITLE
no documentation for the Book class

### ISSUE THREAD

**Issue by sunito** [Thomas008/robust_excel_ole#1]
Hello,

while the documentation of RobustExcelOle::Excel is very useful for me, 
I regret that this kind of doc does not seem to exist for RobustExcelOle::Book,
at least not on rubydoc.info:
http://www.rubydoc.info/gems/robust_excel_ole/RobustExcelOle/Book # ==> Oops...
http://www.rubydoc.info/gems/robust_excel_ole/0.3.1/RobustExcelOle/Book # ==> Oops...

I would be glad, if you could fix this
Thanks
Sven

**Comment by Thomas008** [comment]
Hello,
at last we found out how to fix it.
For ruby 1.8.x the option --legacy in the yardopts file was needed.
Thanks
Thomas
