### ISSUE TITLE
Range documentation, particularly pasting range values

### ISSUE THREAD

**Issue by shbeavers** [Thomas008/robust_excel_ole#11]
I think confusing documentation is masking many great new capabilities implemented with the addition of new range features.  As a start, clarification is needed on the following points:
- The range documentation does not seem to describe how to paste a range, that is, how to paste the values in a range into another range location.  How, for example, does one copy the values from sheet("A1:A6") to sheet("B7:B12)?
- There is no mention of a range.paste method that corresponds to range.copy.  Does a range.paste method exist?
- It's unclear why range.copy is even needed - it seems like simply declaring a range delivers the 'copy' functionality.  Which begs the question, what is actually meant by the expression "accessing a range"?
- If you can paste a range, do you just specify the upper left cell of the area to paste into?
- For some reason it seems it's only possible to paste a single cell into another Excel instances but it's not clear what's different about the the rules for pasting into another worksheet or workbook in the same Excel instance.
- For the vast majority of the examples it's not evident what the advantage is to using a range over simply working with the methods of a single cell.

**Comment by shbeavers** [comment]
After much more experimentation I can address most of the points I raised in this issue:
 - The range.copy method also does the pasting so there is no corresponding range.paste method.  The method naming is confusing because 'copy' is not 'copy' in usual sense of being the first part of 'copy and paste' where selected values are copied to the clipboard and then pasted from it.  Instead 'copy' is more of a 'copy_into' method where 'range=sheet.range' has defined the selected cells to copy from and range.copy specifies the upper left cell of the location to copy into.  So range.copy does the copy and paste as one action instead of the usual two.
- Therefore "accessing" a range is whatever you might like it for:  cutting, copying, making text bold, etc.
- This understanding makes it clear that the advantage of the range method is just what you would expect - that actions may be performed on a group of cells all at once rather than by looping through each individual cell one at a time.
- The only thing that is still uncertain is the distinction made by the documentation in functionality between Excel instances versus between workbooks and worksheets (which are presumably encompassed by the same Excel instance).

I do believe the documentation would be greatly improved by explicitly spelingl out the difference between the range 'copy' method and the usual meaning of 'copy' as a document utility function that is closely coupled to 'paste'.  Renaming the method to 'copy_to' or 'copy_into' would also make things clearer.

**Comment by shbeavers** [comment]
Reopening issue because I accidentally closed it when just meaning to add a comment.

**Comment by Thomas008** [comment]
Here is an improved descrition now available in Readme_ranges:

Let's assume, you have a source range

  src_range = sheet.range(1..2,3..5)

or, in A1-format,

  src_range = sheet.range("C1:E2")

To copy it, you provide a destination range of the same size.

  dest_range = sheet2.range(4..5,6..8)

or, in A1-format
  
  dest_range = sheet2.range("F4:H5")

Now you can copy the values only by assigning the values with help of the VBA methods.

  dest_range.Value = src_range.Value

If you know about the destination range only the left top cell, e.g. [4,6], but don't want to care about the size of the source and destination range,
then you can use in this case

   dest_range = sheet2.range(4..4+src_range.Rows.Count,6..6+src_range.Columns.Count)

   dest_range.Value = src_range.Value

If you want to transpose the range you can use 
  
  dest_range = sheet2.range(4..6,6..7)
  dest_range.Value = dest_range.worksheet.workbook.excel.WorksheetFunction.Transpose(src_range)

If you want to copy not only the values but also formatting, cell formulas, etc., then you can use the VBA method Copy

   src_range.Copy(:destination => dest_range.ole_range)

or you use the RobustExcelOle method "copy" by providing the destination address and the destination worksheet

   src_range.copy([4..5,6..8],sheet2)

The RobustExcelOle method +copy+ allows to copy a range not only into another worksheet and in another workbook, but also into another Excel instance. Note, that when copying into another Excel instance, the clipboard is being used. Furthermore, the destination range shall be a cell (a rectangular range destination is not being considered). 

  book2 = Workbook.open('spec/data/another_workbook.xls', :excel => :new, :visible => true)
  range.copy([5,8],book2.sheet(3))

**Comment by Thomas008** [comment]
Let's assume, you have a source range

  src_range = sheet.range(1..2,3..5)

or, in A1-format,

  src_range = sheet.range("C1:E2")

To copy it, you provide a destination range of the same size.

  dest_range = sheet2.range(4..5,6..8)

or, in A1-format,
  
  dest_range = sheet2.range("F4:H5")

Now you can copy the values only by assigning the values with help of the VBA methods.

  dest_range.Value = src_range.Value

If you know about the destination range only the left top cell, e.g. [4,6], but don't want to care about the size of the source and destination range,
then you can use in this case

   dest_range = sheet2.range(4..4+src_range.Rows.Count,6..6+src_range.Columns.Count)

   dest_range.Value = src_range.Value

If you want to transpose the range you can use 
  
  dest_range = sheet2.range(4..6,6..7)
  dest_range.Value = dest_range.worksheet.workbook.excel.WorksheetFunction.Transpose(src_range)

If you want to copy not only the values but also formatting, cell formulas, etc., then you can use the VBA method Copy

   src_range.Copy(:destination => dest_range.ole_range)

or you use the RobustExcelOle method +copy+ by providing the destination address and the destination worksheet

   src_range.copy([4..5,6..8],sheet2)

The RobustExcelOle method +copy+ allows to copy a range not only into another worksheet and in another workbook, but also into another Excel instance. Note, that when copying into another Excel instance, the clipboard is being used. Furthermore, the destination range shall be a cell (a rectangular range destination is not being considered). 

  book2 = Workbook.open('spec/data/another_workbook.xls', :excel => :new, :visible => true)
  range.copy([5,8],book2.sheet(3))
