### ISSUE TITLE
Double letter column addresses not recognized

### ISSUE THREAD

**Issue by shbeavers** [Thomas008/robust_excel_ole#12]
Trying to address a partial row with the range(["S2:DP2"]) produces a failure with this error:  "address (["S2:DP2"]) not in A1- or R1C1-format".  This is documented as an acceptable A1 addressing format.  If the documentation is correct then the problem would appear to be that double-letter column ranges beyond 'Z' are not understood correctly by Robust.

**Comment by Thomas008** [comment]
Bug fix: Now several letter column addresses are correctly recognized. 
Thank you for pointing this out.

**Comment by shbeavers** [comment]
My pleasure as always, Thomas.  Be well.
