### ISSUE TITLE
method_missing when testing "example_open" file 

### ISSUE THREAD

**Issue by lsq** [Thomas008/robust_excel_ole#16]
C:/Users/Administrator/robust_excel_ole/lib/robust_excel_ole/workbook.rb:928:in `method_missing': (in OLE method `Window
s': ) (WIN32OLERuntimeError)
    OLE error code:8002000B in <Unknown>
      <No Description>
    HRESULT error code:0x80020009
      Exception occurred.

**Comment by Thomas008** [comment]
Hello,

thank you for pointing out this error.

Could you please give more details, e.g. the full trace, and the Excel version and ruby version you are using.

I can't reproduce this error, i.e., it is working in my system.

Best regards,

Thomas
 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Sonntag, 21. April 2019 um 12:04 Uhr
Von: "lsq" <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Thomas008/robust_excel_ole] method_missing when testing "example_open" file (#16)


C:/Users/Administrator/robust_excel_ole/lib/robust_excel_ole/workbook.rb:928:in method_missing': (in OLE method Window
s': ) (WIN32OLERuntimeError)
OLE error code:8002000B in

HRESULT error code:0x80020009
Exception occurred.

**Comment by Thomas008** [comment]
Hello isq,
can you give a more detailed error report of the "method missing" error?
Best regards,
Thomas

**Comment by lsq** [comment]
Thanks Thomas, the error can't reproduce, it works now.

**Comment by Thomas008** [comment]
Hi,

I have another question to you. I saw on your github page, that you had considered RobustExcelOle as an Excel library.

Would you use it now, or what do you think makes RobustExcelOle unsuitable for Excel applications?

Best regards,

Thomas

 

 



Gesendet: Sonntag, 09. Juni 2019 um 05:27 Uhr
Von: "lsq" <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, Comment <comment@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] method_missing when testing "example_open" file (#16)


Thanks Thomas, the error can't reproduce, it works now.
