### ISSUE TITLE
Excel.new(a_running_ole_excel) creates e new Excel instance

### ISSUE THREAD

**Issue by sunito** [Thomas008/robust_excel_ole#17]
This seems to be a bug. 
Always reproducible in my JRuby 9.2.6.0 (2.5.3)
```
  ole_excel = WIN32OLE.connect("Excel.Application")  
  reo_excel = Excel.new(ole_excel)
  p ole_excel.Hwnd
  p reo_excel.Hwnd   # --> different numbers
```
But actually the window handles should be the same, 
as `reo_excel` should just be a wrapper around `ole_excel`.

**Comment by Thomas008** [comment]
Thank you for pointing this out.
Excel#new for lifting a WIN32OLE object is now debugged.
A condition for applying a workaround for jruby was not sharp enough.
