### ISSUE TITLE
If the workbook is already open, Workbook.unobtrusively(path_to_workbook) should use it

### ISSUE THREAD

**Issue by sunito** [Thomas008/robust_excel_ole#18]
This is a feature request, because I think that the semantics of `Workbook.unobtrusively`
is unnecessarily limited: 
>  Remark: works only for workbooks opened with RobustExcelOle

But simply `WIN32OLE.connect(path_to_workbook)` 
would already give us the workbook object, regardless where it was opened.
I think that RobustExcelOle shouldn't be less powerful than WIN32OLE.
So please do incorporate the ability to connect to unknown workbooks.

**Comment by Thomas008** [comment]
We have now incorporated the ability to connect to unknown workbooks: Workbook.open and Workbook.unobtrusively include connecting to already opened workbooks.
