### ISSUE TITLE
paradoxical behaviour of Excel.close_all

### ISSUE THREAD

**Issue by sunito** [Thomas008/robust_excel_ole#19]
Instead of closing Excel instances, `Excel.close_all` will open one more instance!
This is always reproducible on my JRuby 9.2.6.0 (2.5.3)

**Comment by Thomas008** [comment]
Excel.close_all does not work on JRuby yet. Excel.close_all  relies on stepping through all heap objects in ObjectSpace. In Jruby ObjectSpace is disabled. Each_object will only work with Class.
