### ISSUE TITLE
uninitialized constant RobustExcelOle::Workbook::JRUBY_BUG_CONNECT

### ISSUE THREAD

**Issue by dsisnero** [Thomas008/robust_excel_ole#28]
From: c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb @ line 100 RobustExcelOle::Workbook.new:

     95:       book = nil
     96:       if options[:force][:excel] != :new
     97:         # if readonly is true, then prefer a book that is given in force_excel if this option is set
     98:         forced_excel =
     99:           (options[:force][:excel].nil? || options[:force][:excel] == :current) ?
 => 100:             (excel_class.new(:reuse => true) if !JRUBY_BUG_CONNECT) : excel_of(options[:force][:excel])
    101:         begin
    102:           book = if File.exists?(file)
    103:             bookstore.fetch(file, :prefer_writable => !(options[:read_only]),
    104:                                   :prefer_excel    => (options[:read_only] ? forced_excel : nil))
    105:           end
[7] pry(RobustExcelOle::Workbook)> step
Traceback (most recent call last):
        4: from lib/nexcom/cost_estimate.rb:276:in `<main>'
        3: from lib/nexcom/cost_estimate.rb:276:in `new'
        2: from lib/nexcom/cost_estimate.rb:183:in `initialize'
        1: from c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb:125:in `open'
c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb:100:in `new': uninitialized constant RobustExcelOle::Workbook::JRUBY_BUG_CONNECT (NameError)

**Comment by Thomas008** [comment]
Thank you for pointing this out! We are going to fixing this bug.
It comes from a workaround for managing shortcomings in jruby.

Best regards


 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Donnerstag, 13. Februar 2020 um 01:59 Uhr
Von: "dsisnero" <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Thomas008/robust_excel_ole] uninitialized constant RobustExcelOle::Workbook::JRUBY_BUG_CONNECT (#28)


From: c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb @ line 100 RobustExcelOle::Workbook.new:

 95:       book = nil

 96:       if options[:force][:excel] != :new

 97:         # if readonly is true, then prefer a book that is given in force_excel if this option is set

 98:         forced_excel =

 99:           (options[:force][:excel].nil? || options[:force][:excel] == :current) ?



=> 100: (excel_class.new(:reuse => true) if !JRUBY_BUG_CONNECT) : excel_of(options[:force][:excel])
101: begin
102: book = if File.exists?(file)
103: bookstore.fetch(file, :prefer_writable => !(options[:read_only]),
104: :prefer_excel => (options[:read_only] ? forced_excel : nil))
105: end
[7] pry(RobustExcelOle::Workbook)> step
Traceback (most recent call last):
4: from lib/nexcom/cost_estimate.rb:276:in <main>' 3: from lib/nexcom/cost_estimate.rb:276:in new'
2: from lib/nexcom/cost_estimate.rb:183:in initialize' 1: from c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb:125:in open'
c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb💯in `new': uninitialized constant RobustExcelOle::Workbook::JRUBY_BUG_CONNECT (NameError)

**Comment by Thomas008** [comment]
Can you describe please a line from the call of RobustExcelOle?
I have commited and pushed a bug fix. Please tell us, whether it works.

Thank you a lot!

Best regards, Thomas


 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Donnerstag, 13. Februar 2020 um 01:59 Uhr
Von: "dsisnero" <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Thomas008/robust_excel_ole] uninitialized constant RobustExcelOle::Workbook::JRUBY_BUG_CONNECT (#28)


From: c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb @ line 100 RobustExcelOle::Workbook.new:

 95:       book = nil

 96:       if options[:force][:excel] != :new

 97:         # if readonly is true, then prefer a book that is given in force_excel if this option is set

 98:         forced_excel =

 99:           (options[:force][:excel].nil? || options[:force][:excel] == :current) ?



=> 100: (excel_class.new(:reuse => true) if !JRUBY_BUG_CONNECT) : excel_of(options[:force][:excel])
101: begin
102: book = if File.exists?(file)
103: bookstore.fetch(file, :prefer_writable => !(options[:read_only]),
104: :prefer_excel => (options[:read_only] ? forced_excel : nil))
105: end
[7] pry(RobustExcelOle::Workbook)> step
Traceback (most recent call last):
4: from lib/nexcom/cost_estimate.rb:276:in <main>' 3: from lib/nexcom/cost_estimate.rb:276:in new'
2: from lib/nexcom/cost_estimate.rb:183:in initialize' 1: from c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb:125:in open'
c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/robust_excel_ole-1.13/lib/robust_excel_ole/workbook.rb💯in `new': uninitialized constant RobustExcelOle::Workbook::JRUBY_BUG_CONNECT (NameError)

**Comment by dsisnero** [comment]
Did you update the gem?  I tried updating it but nothing came up.  I then cloned the repo and did a bundle install and tried to build it but got errors

An error occurred while loading ./spec/reo_common_spec.rb.
Failure/Error:
  File.open(reo_log_dir + '/' + REO_LOG_FILE,'a') do |file|
    file.puts text
  end

Errno::ENOENT:
  No such file or directory @ rb_sysopen - C:/Users/User/reo.log

**Comment by dsisnero** [comment]
form ||= CostEstimate::EXCEL_FILE.to_s
      @wb = RobustExcelOle::Workbook.open(form, visible:
true,if_obstructed: :forget,if_unsaved: :forget)

**Comment by Thomas008** [comment]
Please find the updated ruby gem, in github or rubygems, hoping it works.

Thank you again for pointing out the bugs.

We are happy for any further wishes, feature requests or feedbacks for your applications.

Best regards,

Thomas
 

---

 
 

form ||= CostEstimate::EXCEL_FILE.to_s
@wb = RobustExcelOle::Workbook.open(form, visible:
true,if_obstructed: :forget,if_unsaved: :forget)
