### ISSUE TITLE
ListObject support

### ISSUE THREAD

**Issue by sunito** [Thomas008/robust_excel_ole#30]
As far as I know, the library does not offer any support for **table objects** (called ListObjects in the VBA object model). 

In most cases, I am fine with just using VBA to manipulate table objects, but in some situations this gets a little cumbersome. 
For example, always having to check if the table is empty (i.e. if there are any ListRows) is a PITA. ;) 

So, I am requesting a more streamlined interface to table objects, which, for example, 
would provide a single method for deleting the content rows of the table.

**Comment by Thomas008** [comment]
RobustExcelOle supports now table objects (List Objects in VBA terms).
There are methods for adding and deleting contents in rows and columns in the table, for reading and setting values in the table, for finding cells that contain a given value, sorting a table, and so on. Of course, all VBA methods can be applied to the table object.
